swagger: "2.0"
info:
  description: "REST API"
  version: "1.0.1"
  title: "REST API for the MFC mobile application"
  contact:
    email: "d.shitov@artepay.ru"
host: "127.0.0.1"
basePath: "/api"
tags:
- name: "service"
  description: "Quality of service questionnaire"
  externalDocs:
    description: "Description of the interaction"
    url: "http://smev.gosuslugi.ru/portal/api/files/registryfile/28653/%D0%A0%D0%9F_%D0%A1%D0%B5%D1%80%D0%B2%D0%B8%D1%81_%D0%B0%D0%BA%D1%82%D1%83%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8_%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D0%BD%D0%BE%D0%B9_%D1%84%D0%BE%D1%80%D0%BC%D1%8B_%D0%BE_%D0%BA%D0%B0%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5_%D1%83%D1%81%D0%BB%D1%83%D0%B3_v_1_2.doc"
schemes:
- "https"
- "http"
paths:
  /api/service/info:
    get:
      tags:
      - "service"
      summary: "Service information"
      description: "return information about the questionnaire"
      operationId: "infoService"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Service"
        400:
          description: "Invalid request"
  /api/service/direct:
    get:
      tags:
      - "service"
      summary: "Service type - direct"
      description: "Returns information about the form fields of the questionnaire"
      operationId: "directService"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Service"
        400:
          description: "Invalid request"
  /api/service/electronic:
    get:
      tags:
      - "service"
      summary: "Service type - electronic"
      description: "Returns information about the form fields of the questionnaire"
      operationId: "electronicService"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Service"
        400:
          description: "Invalid request"
definitions:
  Service:
    type: "object"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"